name: Build and test Docker image develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Test and build dev image

    runs-on: ubuntu-latest

    env:
      PUSH_IMAGE: ${{ github.event_name == 'push' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test Docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: flask-docker:test
          target: test
          platforms: linux/arm/v6

      - if: ${{ env.PUSH_IMAGE }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ env.PUSH_IMAGE }}
        name: Build and push Docker dev image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-docker:dev
          target: development
          platforms: linux/arm/v6
