name: Build and test Docker image develop

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Test Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: marvkosmai/flask-docker:latest
        target: production
        platforms: linux/arm/v6
