name: Build and test Docker image develop

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
    name: Test image

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Test Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: flask-docker:test
        target: test
        platforms: linux/arm/v6
