name: Build and test Docker image develop

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Test Docker image
      run: docker build -t flask-docker --target test --platform linux/arm/v6 .
